### ISSUE TITLE
explain/document "index closed table" as seen in this case

### ISSUE THREAD

**Issue by raould** [andremm/typedlua#25]
https://github.com/raould/typedlua/tree/master/QUESTIONS/2
I do not understand what it means when I get "type error, attempt to use 'renderer' to index closed table" in this case. I am guessing other people will hit this kind of thing and be lost as well :-}. Pretty please document/explain it?

**Comment by raould** [comment]
It looks to me like the statement from the paper that "If a variable gets its type from a table constructor
then it is open, otherwise it is always closed." is not how the implementation does it? I am using stuff like
local m = {} -- shouldn't this mean the table is open? 
m.setFoo(foo:any)
  m.foo = foo
end
return m
I am assuming that an "open" table would then not lead to these various "attempt to use foo to index closed table" sorts of type checking errors?

**Comment by raould** [comment]
Guess the variable mentioned in the paper is not the table but rather things inside it. But im still confised how to make a local open table. looking at the nice test cases, i havent seen what causes my attempts to fail. Looks like maybe aliasing is the tjing in tests that give closed tables maybe, but i dont know that my examples / attempts use aliasing.

**Comment by andremm** [comment]
Hi,

```
local Drawer = {renderer=nil}
```
fails because `renderer` is not included in the type of `Drawer` since it is `nil`.

```
local Drawer = {} -- fails
```
fails because `renderer` is not present in the type of `Drawer`.

The table is open only in the same scope that it was declared. So, when you enter a function definition, all open tables become closed and you cannot add new fields to them.

I'm working on a better documentation about them, but it will take some time to get done, as I'm working in several stuffs at the same time. Sorry.

**Comment by raould** [comment]
Than you for the info, I will try to digest!
