### ISSUE TITLE
Please expound upon table type checking

### ISSUE THREAD

**Issue by raould** [andremm/typedlua#27]
hi, I am still lost about table type checking, for maps & arrays. I can't seem to get things to pass. See e.g. https://github.com/raould/typedlua/tree/master/QUESTIONS/3

player.tl:12:10: type error, attempt to assign '({number:(number | nil)} | nil)' to '{number:(number | nil)}'
I do not understand how the extra "| nil)" gets in there for the first half of that error.

**Comment by andremm** [comment]
Hi, maps and arrays always include the type `nil`, as Lua returns `nil` when we index a table with a key that does not exist in this table. Closed table types means that you cannot use field assignment to add new fields to this table.
I guess you may want to annotate your example as follows:
`
local points:{{number}} =  {{1,2}, {3,4}}
local lines:{{{number}}} = {}
for i = 1, #points-1 do
   local pt1:{number}? = points[i]
   local pt2:{number}? = points[i+1]
   lines[i] = {pt1, pt2}
end
table.insert(lines, #lines + 1, {points[#points], points[1]})
`
Note that you need `#lines + 1` while calling `table.insert` because this is an overloaded function, but Typed Lua is set to handle the case that you give the position where the element should be inserted.

**Comment by raould** [comment]
Thank you, making more sense to my slow brain a little now. :-)
