### ISSUE TITLE
Allowing references to methods

### ISSUE THREAD

**Issue by andremm** [andremm/typedlua#67]
I believe the following code should compile with a warning about the method reference that is being created in the last line.

```lua
local o = { x = 1.0 }
const function o:set_x (x:number) self.x = x end
local x = o.set_x
```

This is a test case in `test.lua` that is failing to pass.

**Comment by mascarenhas** [comment]
Creating method references is really unsafe, because of method redefinition (a self parameter is covariant when a method is redefined, but function parameters are supposed to be contravariant only). I think the proper way to solve this is to replace "self" with "any" capturing a method reference, so `x` above would be `(any, number) -> void`.

BTW, self should have more restrictions: self in a method type should only appear either in the first parameter or in the return type. Otherwise it is unsafe even if method references are not taken. I can look into this.

**Comment by mascarenhas** [comment]
Done in commit 7a1968abd003c647c6356d85aa5a9486aa5cdbdf
